# Generated by Django 4.2 on 2024-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=150)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('is_done', models.BooleanField(blank=True, default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('deleted_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
